name: tfsec

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**.yml"
      - "!.github/workflows/tfsec.yml"
      - "README.md"
      - ".gitignore"
  schedule:
    - cron: "0 6 1 * *"

concurrency: ${{ github.workflow }}

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Scan
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
